server:
  port: 8089
  servlet:
    context-path: /user-provider
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/treval?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
  application:
    name: user-provider   #服务提供者

ribbon:
  #轮询
  NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
  ConnectTimeout: 10000 # 连接超时时间
  ReadTimeout: 2000 # 数据读取超时时间
  MaxAutoRetries: 1 # 最大重试次数(第一个服务)
  MaxAutoRetriesNextServer: 0 # 最大重试下一个服务次数(集群的情况才会用到)
  OkToRetryOnAllOperations: false # 无论是请求超时或者socket read timeout都进行重试

eureka:
  client:
    service-url:
      #提供eureka
      defaultZone: http://localhost:8000/eureka
    #每隔30秒获取服务中心列表,(只读备份)
    register-fetch-interval-seconds: 30
  instance:
    #指定ip地址
    ip-address: 127.0.0.1
    #访问服务的时候,推曾使用ip
    perfer-ip-address: true
    #租约到期,服务时效时间,默认值90秒
    lease-expiration-duration-in-seconds: 90
    #租约续约间隔时间,默认30秒
    lease-renewal-interval-in-seconds: 30
logging:
  level:
    com.lixun: debug
test:
  message: hello

